name: Mac

# only build on push of tags
on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ${{ matrix.arch == 'arm64' && 'macos-14' || 'macOS-13' }}
    timeout-minutes: 60
    strategy: 
      matrix:
        arch: [arm64, x86-64]
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: install host sbcl
      run: brew install sbcl
    - name: build
      run: |
        ./configure --with-lisp=sbcl --enable-distribution
        make
        ls
        pwd
    #- name: save binary
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: cafeobj-sbcl-${{ matrix.arch }}-darwin
    #    path: cafeobj-*-sbcl-*Darwin.tar.gz
    - name: check
      run: |
        ls
        echo "======"
        pwd
        echo "======"
        ls ${{ github.workspace }}
        echo "======"
    - name: Release
      uses: AButler/upload-release-assets@v3.0
      with:
        files: cafeobj-*-sbcl-*Darwin.tar.gz
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ github.ref_name }}

